services:
  backend:
    build:
      context: ./backend # Path to the Spring Boot backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app:delegated
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test_canteen_app_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend # Path to the React frontend
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/app:delegated
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_canteen_app_db
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql:delegated
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
